debug: false

spring:
  config:
    use-legacy-processing: true
  profiles:
    active: dev, swagger

  cloud:
    consul: #disabled for dev
      enabled: false
      discovery:
        enabled: false
        register: false

multipart:
  enabled: true

spring.servlet.multipart.max-file-size: -1
spring.servlet.multipart.max-request-size: -1

server:
  host:
  port: 8089
  ssl:
    key-store: src/main/resources/dev/keystore_archive-search-external.jks
    key-store-password: changeme
    key-password: changeme
    trust-store: src/main/resources/dev/truststore_server.jks
    trust-store-password: changeme
    client-auth: need
    enabled-protocols: TLSv1.2,TLSv1.3
    ciphers: ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384

management:
  server:
    address: localhost
    port: 8189
    ssl:
      enabled: false

archive-search-external:
  security-client:
    server-host: localhost
    server-port: 8084
    secure: false
  iam-internal-client:
    server-host: localhost
    server-port: 7083
    secure: false
  archive-search-internal-client:
    server-host: localhost
    server-port: 7089
    secure: false

# Jaeger
opentracing:
  jaeger:
    enabled: true
    logSpans: true
    expandExceptionLogs: true
    udp-sender:
      host: localhost
      port: 6831

logging:
  level:
    fr.gouv.vitamui: DEBUG
    fr.gouv.vitamui.iam.security: DEBUG
    #level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG


---
spring:
  config:
    activate:
      on-profile: gateway

gateway:
  enabled: true
server:
  ssl:
    client-auth: want
    client-certificate-header-name: x-ssl-cert
