spring:
  profiles:
    active: dev,swagger

  cloud:
    consul:  #disable for dev
      enabled: false
      discovery:
        enabled: false
        register: false

ui-identity:
  #theme-logo: /path/to/logo.png
  platform-name: VITAM-UI
  theme-colors:
    vitamui-primary: "#ff4a54"
    vitamui-secondary: "#241f63"
  assets: src/main/config
  iam-external-client:
    server-host: localhost
    server-port: 8083
    secure: true
    ssl-configuration:
      keystore:
        key-path: ../../dev-deployment/environments/keystores/server/localhost/keystore_ui-identity-admin.jks
        key-password: changeme
        type: JKS
      truststore:
        key-path: ../../dev-deployment/environments/keystores/server/truststore_server.jks
        key-password: changeme
      hostname-verification: false
  base-url:
    portal: "https://dev.vitamui.com:4200"
  portal-categories:
    ingests:
      title: "Suivi des Versements"
      displayTitle: true
      order: 4
    administrators:
      title: "Management"
      displayTitle: true
      order: 2
    settings:
      title: "Param√©trage"
      displayTitle: true
      order: 3
    users:
      title: ""
      displayTitle: false
      order: 1

server:
  host: dev.vitamui.com
  port: 9001
  scheme: https
  ssl:
    key-store: ../../dev-deployment/environments/keystores/server/localhost/keystore_ui-identity-admin.jks
    key-store-password: changeme
    key-password: changeme
  servlet.session.cookie.path: /identity-api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

management:
  server:
    address: localhost
    port: 9101
    ssl:
      enabled: false

ui:
  url: "https://dev.vitamui.com:4201"
  redirect-url: https://dev.vitamui.com:9001/${ui-prefix}

cas:
  internal-url: https://dev.vitamui.com:8080/cas
  external-url: https://dev.vitamui.com:8080/cas
  callback-url: ${ui.url}/identity-api/callback
  ssl:
    trust-store: ../../dev-deployment/environments/keystores/server/truststore_server.jks
    trust-store-password: changeme

# Uncomment if you want to use you specific logback config.
#logging:
# config: src/main/config/logback.xml

debug: false
logging:
  level:
    fr.gouv.vitamui: DEBUG
    fr.gouv.vitamui.commons.rest.AbstractRestController: INFO

management.endpoints.web.exposure.include: "*"
